### ISSUE TITLE
why should there delete previousLoad?

### ISSUE THREAD

**Issue by zixun** [tauon/menustat#1]
`load.busy -= previousLoad![i].busy`

https://github.com/tauon/menustat/blob/8f40c9cace8a9a7d62f136ee0ff407b2374713d5/menustat/CPUInfo.swift#L47

**Comment by tauon** [comment]
previousLoad.busy is *total* busy ticks up to previous measurement; we subtract this from current measurement total busy load ticks to get the delta.
